### ISSUE TITLE
怎么广播？

### ISSUE THREAD

**Issue by miaomiao1992** [luyikk/tcp_server#1]
如题

**Comment by luyikk** [comment]
peer clone 一份到 容器，迭代容器即可

**Comment by miaomiao1992** [comment]
> peer clone 一份到 容器，迭代容器即可

大佬，我悟了，我发现writeHalf和readhalf 的写和读方法都是&self，套个Arc就能轻松克隆了

**Comment by luyikk** [comment]
> > peer clone 一份到 容器，迭代容器即可
> 
> 大佬，我悟了，我发现writeHalf和readhalf 的写和读方法都是&self，套个Arc就能轻松克隆了

一般 read 不需要移动， peer 挪走就行了，如果需要 广播 peer 克隆一份 到容器 ，断线的时候 从容器清除就好了

peer 自身 自带 arc 可克隆
https://github.com/luyikk/tcp_server/blob/a81ba3c6617cecd9be980570174df2894940b3a6/src/peer.rs#L20

**Comment by miaomiao1992** [comment]
> > > peer clone 一份到 容器，迭代容器即可
> > 
> > 
> > 大佬，我悟了，我发现writeHalf和readhalf 的写和读方法都是&self，套个Arc就能轻松克隆了
> 
> 一般 read 不需要移动， peer 挪走就行了，如果需要 广播 peer 克隆一份 到容器 ，断线的时候 从容器清除就好了
> 
> peer 自身 自带 arc 可克隆
> 
> https://github.com/luyikk/tcp_server/blob/a81ba3c6617cecd9be980570174df2894940b3a6/src/peer.rs#L20

大佬，不行啊，accept后用了tokio::spawn，没法用容器啊

**Comment by miaomiao1992** [comment]
tcp stream的读写回调都在tokio::spawn里面，没法在这里面创建一个容器

**Comment by luyikk** [comment]
> tcp stream的读写回调都在tokio::spawn里面，没法在这里面创建一个容器


通过 start 传入
