### ISSUE TITLE
use aqueue::Actor有啥用？

### ISSUE THREAD

**Issue by miaomiao1992** [luyikk/tcp_server#2]
没看明白

**Comment by luyikk** [comment]
Actor 模型， 保证 里面套的东西 操作逻辑的时候 是 线程安全 队列执行

**Comment by luyikk** [comment]
https://github.com/luyikk/tcp_server/blob/a81ba3c6617cecd9be980570174df2894940b3a6/src/peer.rs#L34 这里是 内部是可修改 借用，对自身，
https://github.com/luyikk/tcp_server/blob/a81ba3c6617cecd9be980570174df2894940b3a6/src/peer.rs#L109 而这里 对外确实 只读借用

同时又为了保证 多个线程 对 send的有序调用执行
